blockscout/frontend

- ui/shared/DetailsSponsoredItem.tsx
Fix [#1146 ](https://github.com/blockscout/frontend/issues/1146)
> Fixed issue with empty 'Sponsored' text prompt without AdBanner in DetailsInfoItem of TokenDetails Page.

- configs/app/features/restApiDocs.ts
- configs/envs/.env.eth
- configs/envs/.env.eth_goerli
- configs/envs/.env.localhost
- configs/envs/.env.main
- configs/envs/.env.main.L2
- configs/envs/.env.poa_core
- configs/envs/.env.polygon
- configs/envs/.env.rootstock
- deploy/values/l2-optimism-goerli/values.yaml
- deploy/values/main/values.yaml
- deploy/values/review-l2/values.yaml.gotmpl
- deploy/values/review/values.yaml.gotmpl
- docs/ENVS.md
resolves https://github.com/blockscout/frontend/issues/1162
> default spec url

- lib/mixpanel/getPageType.ts
- lib/mixpanel/useLogPageView.tsx
- lib/mixpanel/utils.ts
- ui/address/contract/ContractConnectWallet.tsx
- ui/address/contract/ContractMethodCallable.tsx
- ui/address/details/AddressFavoriteButton.tsx
- ui/address/details/AddressQrCode.tsx
- ui/address/tokenSelect/TokenSelect.tsx
- ui/address/tokenSelect/TokenSelectButton.tsx
- ui/addressVerification/AddressVerificationModal.tsx
- ui/addressVerification/steps/AddressVerificationStepSignature.tsx
- ui/contractVerification/ContractVerificationForm.tsx
- ui/pages/UnverifiedEmail.tsx
- ui/pages/VerifiedAddresses.tsx
- ui/privateTags/AddressModal/AddressModal.tsx
- ui/privateTags/PrivateAddressTags.tsx
- ui/privateTags/TransactionModal/TransactionForm.tsx
- ui/privateTags/TransactionModal/TransactionModal.tsx
- ui/shared/AddressActions/Menu.tsx
- ui/shared/AddressActions/PrivateTagMenuItem.tsx
- ui/shared/AddressActions/TokenInfoMenuItem.tsx
- ui/snippets/profileMenu/ProfileMenuContent.tsx
- ui/snippets/profileMenu/ProfileMenuDesktop.tsx
- ui/snippets/profileMenu/ProfileMenuMobile.tsx
- ui/tokenInfo/TokenInfoForm.tsx
> More events for mixpanel analytics

- lib/web3/useProvider.tsx
- package.json
- playwright-ct.config.ts
- playwright/mocks/modules/@metamask/post-message-stream.js
- playwright/mocks/modules/@metamask/providers.js
- ui/address/AddressDetails.pw.tsx
- ui/snippets/footer/Footer.pw.tsx
- yarn.lock
> bugfix: MM is not injected in FF

- stubs/stats.ts
- types/api/stats.ts
- ui/stats/NumberWidget.tsx
- ui/stats/NumberWidgetsList.tsx
> Charts&Stats: add tooltips to number charts

- ui/addresses/AddressesListItem.tsx
- ui/addresses/AddressesTable.tsx
- ui/addresses/AddressesTableItem.tsx
- ui/pages/Accounts.tsx
> Top accounts percentage of funds is not displayed correctly

- ui/shared/tx/TxFeeStability.tsx
- ui/txs/TxAdditionalInfoContent.tsx
resolves https://github.com/blockscout/frontend/issues/1304
> stability fixes

- pages/api/proxy.ts
- ui/address/AddressContract.tsx
- ui/address/contract/ContractRead.tsx
- ui/address/contract/useWatchAccount.tsx
> show "Read contract" tab even if WalletConnect is not configured

- deploy/scripts/download_assets.sh
> support local file URI for ENVs with external resources

- ui/address/contract/utils.test.ts
- ui/address/contract/utils.ts
> Overloaded method with different number of arguments can't be invoked

- lib/api/resources.ts
- types/api/account.ts
- ui/pages/Watchlist.tsx
- ui/privateTags/AddressTagTable/AddressTagTable.tsx
- ui/privateTags/DeletePrivateTagModal.tsx
- ui/privateTags/PrivateAddressTags.tsx
- ui/privateTags/PrivateTransactionTags.tsx
- ui/privateTags/TransactionTagTable/TransactionTagTable.tsx
- ui/shared/pagination/useQueryWithPages.ts
- ui/watchlist/WatchlistTable/WatchlistTable.tsx
resolves https://github.com/blockscout/frontend/issues/1264
> watchlist and private tags pagination

- ui/shared/pagination/Pagination.tsx
- ui/shared/pagination/useQueryWithPages.test.tsx
- ui/shared/pagination/useQueryWithPages.ts
resolves https://github.com/blockscout/frontend/issues/1388
> fix canGoBackwards

- ui/address/SolidityscanReport.tsx
- ui/pages/Address.tsx
resolves https://github.com/blockscout/frontend/issues/1418
> soldity check only for validated contracts + keys fix

- pages/apps/index.tsx
- ui/pages/Marketplace.tsx
Resolves https://github.com/blockscout/frontend/issues/1430
> Move `submit app` button

- ui/shared/layout/LayoutApp.tsx
After the last release, there is an extra padding and the top bar is missing.
> Fix layout for marketplace app page

- types/api/stats.ts
- ui/home/Stats.tsx
- ui/shared/GasInfoTooltipContent/GasInfoTooltipContent.tsx
- ui/snippets/topBar/TopBarStats.tsx
fixes https://github.com/blockscout/frontend/issues/1474
> null gas prices

- ui/snippets/walletMenu/WalletTooltip.tsx
- automatically show the tooltip only on the marketplace page
- increase the auto-hide time from 3 to 5 seconds
- add a 1 second delay before showing the tooltip to allow the page to load a bit
> Fix wallet tooltip

- .github/workflows/publish-image.yml
Current GA workflow generates Docker image for a single platform (amd64). There is a demand to make it multiplatform.
Resolves https://github.com/blockscout/frontend/issues/1494
Adds arm64 Docker image generation in `.github/workflows/publish-image.yml` workflow.
> Generate multiplatform image

- .github/workflows/publish-image.yml
- .github/workflows/release.yml
Added input to "Publish image" workflow in order to build multiplatform image only for new release.
> Input for platforms in "publish image" workflow

- ui/tx/TxDetailsDegraded.tsx
when txReceipt.effectiveGasPrice is `nill` can't call txReceipt.effectiveGasPrice.toString() , see 
https://github.com/blockscout/frontend/blob/fe81cfe66ce8f80419e1399bc18832abf03713a5/ui/tx/TxDetailsDegraded.tsx#L69-L80
> fix(tx): when txReceipt.effectiveGasPrice is nill can't call txReceipt.effectiveGasPrice.toString()

- lib/web3/client.ts
- ui/block/useBlockQuery.tsx
- ui/block/useBlockTxQuery.tsx
- ui/block/useBlockWithdrawalsQuery.tsx
- ui/pages/Address.tsx
- ui/pages/Transaction.tsx
- ui/tx/TxDetails.tsx
- ui/tx/TxDetailsDegraded.tsx
- ui/tx/TxUserOps.tsx
- ui/userOps/UserOpsContent.tsx
> Do not send user operations API requests, if NEXT_PUBLIC_HAS_USER_OPS is not enabled

- docs/CONTRIBUTING.md
The specified command for running the dev server with a pre-defined config was incorrect.
Changed `yarn dev:<config_name>` to `yarn dev:preset <config_name>`.
> typo: incorrect yarn dev preset command

- deploy/tools/envs-validator/schema.ts
- types/client/marketplace.ts
- ui/marketplace/MarketplaceAppAlert.tsx
- ui/marketplace/MarketplaceAppInfo.tsx
- ui/marketplace/MarketplaceAppInfo/Content.tsx
- ui/marketplace/MarketplaceAppInfo/SocialLink.tsx
- ui/marketplace/MarketplaceAppInfo/TriggerButton.tsx
- ui/marketplace/MarketplaceAppInfo/WebsiteLink.tsx
- ui/marketplace/MarketplaceAppModal.tsx
- ui/marketplace/MarketplaceAppTopBar.tsx
- ui/pages/MarketplaceApp.tsx
- ui/shared/layout/LayoutApp.tsx
Resolves https://github.com/blockscout/frontend/issues/1603
> Add a top bar to the dapp page

- ui/pages/OptimisticL2Deposits.tsx
- ui/pages/ShibariumDeposits.tsx
Wrong text displayed when no deposits exist. Fixes #1664.
Changed the text _There are no withdrawals_ to _There are no deposits_ in the deposits section when no deposits exist.
None
> Fix message shown when there are no deposits on L2

- .github/workflows/checks.yml
- ui/address/AddressTxs.tsx
- ui/txs/sortTxs.test.ts
- ui/txs/sortTxs.ts
- ui/txs/useTxsSort.tsx
> bugfix: Real-time incoming transactions are sorted incorrectly

- lib/mixpanel/utils.ts
fix a typo: `interpratetion`->`interpretation`
> chore: fix typos

- package.json
- yarn.lock
Resolves https://github.com/blockscout/frontend/issues/1660
The previous version of `dappscout-iframe` was mistakenly published without the necessary changes 😥
> Upgrade `dappscout-iframe`

- deploy/values/review/values.yaml.gotmpl
- ui/address/contract/methodForm/useArgTypeMatchInt.tsx
- ui/address/contract/methodForm/useFormatFieldValue.tsx
- ui/address/contract/methodForm/useValidateField.tsx
- ui/address/contract/methodForm/utils.ts
> Numbers over 16(?) digits are rounded in contract method fields

- lib/hooks/useAdblockDetect.tsx
- nextjs/csp/policies/ad.ts
resolves https://github.com/blockscout/frontend/issues/1772
> adblock detect improvement

- ui/address/ensDomains/AddressEnsDomains.tsx
- ui/shared/NetworkExplorers.tsx
- ui/shared/PopoverTriggerTooltip.tsx
- ui/shared/solidityscanReport/SolidityscanReportButton.tsx
resolves https://github.com/blockscout/frontend/issues/1784
> Add tips to score, explorers, domains

- ui/marketplace/MarketplaceListWithScores.tsx
- ui/marketplace/useMarketplaceApps.tsx
Fixes https://github.com/blockscout/frontend/issues/1804
> Fix marketplace sorting

- deploy/values/review/values.yaml.gotmpl
- lib/socket/types.ts
- mocks/address/tabCounters.ts
- playwright/fixtures/socketServer.ts
- ui/pages/Address.pw.tsx
- ui/pages/Address.tsx
> Get smart-contract bytecode from websocket

- configs/app/chain.ts
- deploy/tools/envs-validator/schema.ts
- docs/ENVS.md
- lib/token/tokenTypes.ts
- ui/address/AddressTokens.tsx
- ui/address/tokenSelect/TokenSelectMenu.tsx
- ui/address/tokens/NFTItem.tsx
- ui/pages/TokenInstance.tsx
- ui/shared/TokenTransfer/TokenTransferListItem.tsx
- ui/shared/TokenTransfer/TokenTransferTableItem.tsx
- ui/shared/filters/TokenTypeFilter.tsx
- ui/shared/search/utils.ts
- ui/token/TokenPageTitle.tsx
- ui/tokens/TokensListItem.tsx
- ui/tokens/TokensTableItem.tsx
- ui/watchlist/AddressModal/AddressFormNotifications.tsx
resolves https://github.com/blockscout/frontend/issues/1955
added NEXT_PUBLIC_NETWORK_TOKEN_STANDARD_NAME variable to configure the display name of a token creation standard
> Add possibility to change ERC to something else

- pages/token/[hash]/instance/[id].tsx
- ui/pages/TokenInstance.tsx
- ui/tokenInstance/TokenInstanceDetails.tsx
> Token Instance Page: move critical requests to the page root

- package.json
- ui/shared/entities/address/AddressIdenticon.tsx
- yarn.lock
> Identicon render issue on `Name details` page on mobile

- lib/growthbook/init.ts
- ui/shared/AppActionButton/useAppActionData.tsx
- ui/token/TokenDetails.tsx
- ui/token/TokenNftMarketplaces.tsx
- ui/tokenInstance/TokenInstanceDetails.pw.tsx
- ui/tokenInstance/TokenInstanceDetails.tsx
- ui/tx/TxSubHeading.pw.tsx
- ui/tx/TxSubHeading.tsx
Resolves https://github.com/blockscout/frontend/issues/1996
> Remove action button experiment

- .github/workflows/deploy-review-l2.yml
- deploy/values/review-l2/values.yaml.gotmpl
- deploy/values/review/values.yaml.gotmpl
Remove variables from the common file, as some instances won't deploy because of this
> Remove marketplace env vars from deployment values

- Dockerfile
Usage of COPY instructions with  '--chmod=+x' works with docker (if buildkit is enabled) but not with [podman](https://github.com/containers/buildah/issues/4614)
Replace '--chmod=+x' with '--chmod=755' for 'COPY' instructions in Dockerfile to be podman-friendly while still supporting docker
Should not break build of container image with docker/podman
Could not test on Windows 10/11 with WSL2 to verify
> replace '--chmod=+x' with '--chmod=755' for 'COPY' instructions in Dockerfile to be podman-friendly

- configs/app/meta.ts
The `NEXT_PUBLIC_PROMOTE_BLOCKSCOUT_IN_TITLE` env is of type `boolean`. It is better to use `===` for strict comparison.
> Fix: using `===` to check `NEXT_PUBLIC_PROMOTE_BLOCKSCOUT_IN_TITLE`

- ui/marketplace/utils.ts
- ui/pages/Marketplace.tsx
Fixes the display of sorting in the marketplace. Now it is displayed only when there are security scores, and also has a rating item even when there is no rating.
> Fix marketplace sorting display

- ui/userOp/UserOpCallData.tsx
- ui/userOp/UserOpDecodedCallData.tsx
> Hide toggle "Show external call data" when data is not available

- lib/api/useApiQuery.tsx
- ui/sol2uml/Sol2UmlDiagram.tsx
> UML diagram caching

- types/api/contract.ts
- types/client/marketplace.ts
- ui/address/SolidityscanReport.tsx
- ui/marketplace/ContractListModal.tsx
- ui/marketplace/ContractSecurityReport.tsx
- ui/shared/solidityscanReport/SolidityscanReportDetails.tsx
resolves https://github.com/blockscout/frontend/issues/2147
> process unexpected response from solidityscan

- nextjs/csp/policies/walletConnect.ts
Lacking *.web3modal.org in CSP header makes walletconnect unable to load icons.
> fix: web3modal csp issue makes walletconnect unable to load icons

- configs/app/chain.ts
- deploy/tools/envs-validator/schema.ts
- deploy/values/review-l2/values.yaml.gotmpl
- deploy/values/review/values.yaml.gotmpl
- docs/ENVS.md
- lib/networks/getNetworkValidationActionText.ts
- types/networks.ts
- ui/address/AddressBlocksValidated.tsx
- ui/address/blocksValidated/AddressBlocksValidatedListItem.tsx
- ui/address/blocksValidated/AddressBlocksValidatedTableItem.tsx
- ui/block/BlockDetails.tsx
- ui/pages/Address.tsx
- ui/pages/Block.tsx
- ui/pages/Transactions.tsx
resolves https://github.com/blockscout/frontend/issues/2067
NEXT_PUBLIC_NETWORK_VERIFICATION_TYPE can't be set for arbutrum and zkevm L2 instances
> change verification type and validator title for Arbitrum and zkEvm

- lib/tx/arbitrumMessageStatusDescription.ts
- types/api/transaction.ts
- ui/tx/details/TxInfo.tsx
resolves https://github.com/blockscout/frontend/issues/2166
> Arbitrum: tx page - add L1 tx

- deploy/values/review/values.yaml.gotmpl
- lib/api/buildUrl.ts
- lib/api/resources.ts
- lib/metadata/getPageOgType.ts
- lib/metadata/templates/description.ts
- lib/metadata/templates/title.ts
- lib/mixpanel/getPageType.ts
- lib/monitoring/metrics.ts
- lib/solidityScan/schema.ts
- lib/solidityScan/useFetchReport.ts
- mocks/contract/solidityscanReport.ts
- nextjs/nextjs-routes.d.ts
- package.json
- pages/api/monitoring/invalid-api-schema.ts
- stubs/contract.ts
- types/api/contract.ts
- types/client/marketplace.ts
- ui/address/SolidityscanReport.pw.tsx
- ui/address/SolidityscanReport.tsx
- ui/marketplace/ContractListModal.tsx
- ui/marketplace/ContractSecurityReport.tsx
- ui/shared/solidityscanReport/SolidityscanReportDetails.tsx
- yarn.lock
- Add validation for SolidityScan API response
- Setup monitoring for "Invalid schema" events - https://grafana.k8s-dev.blockscout.com/d/advprfrl6iwowe/invalid-api-schema-events?orgId=1&from=1724415408310&to=1724437008310
> SolidityScan API response schema validation

- lib/mixpanel/useLogPageView.tsx
- lib/mixpanel/utils.ts
> Mixpanel - add Theme parameter to Page view event

- deploy/tools/favicon-generator/script.sh
Adjust the script to handle special characters in the master URL properly while replacing the placeholder in the config template file.
> Favicon generator: escape special characters in master url

- ui/shared/logs/LogDecodedInputDataHeader.tsx
> Long `Call` field value in `Decoded input data` breaks adaptive UI on mobile

- ui/address/contract/methods/form/ContractMethodFieldInputTuple.tsx
- ui/address/contract/methods/form/utils.test.ts
- ui/address/contract/methods/form/utils.ts
- ui/address/contract/methods/useCallMethodPublicClient.ts
> Fix args length and optional nested arrays in contract method form

- configs/app/features/addressProfileAPI.ts
- configs/app/features/index.ts
- configs/envs/.env.zora
- deploy/tools/envs-validator/schema.ts
- docs/ENVS.md
- lib/hooks/useAddressProfileApiQuery.tsx
- nextjs/csp/generateCspPolicy.ts
- nextjs/csp/policies/index.ts
- nextjs/csp/policies/usernameApi.ts
- tools/preset-sync/index.ts
- types/client/addressProfileAPIConfig.ts
- ui/pages/Address.tsx
resolves https://github.com/blockscout/frontend/issues/2255
added NEXT_PUBLIC_ADDRESS_USERNAME_TAG env variable
config for Zora: `{'api_url_template': 'https://api.zora.co/discover/user/{address}', 'tag_link_template': 'httpszora.co/{username}', 'tag_icon': 'https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/network-icons/zora.svg', 'tag_bg_color': 'rgba(0,0,0)', 'tag_text_color': 'rgba(255,255,255)'}`
> Zora: implement custom tag

- ui/address/blocksValidated/AddressBlocksValidatedListItem.tsx
- ui/address/blocksValidated/AddressBlocksValidatedTableItem.tsx
resolves https://github.com/blockscout/frontend/issues/2281
> Blocks validated skeleton displays placeholder values

- deploy/scripts/entrypoint.sh
This will allow users to handle breaking changes in ENV variables much more easily.
> Add run-time variable to skip ENVs validation

- ui/shared/tx/interpretation/TxInterpretation.tsx
- ui/shared/tx/interpretation/utils.test.ts
- ui/shared/tx/interpretation/utils.ts
resolves https://github.com/blockscout/frontend/issues/2332
> support wei variable in interpretation

- docs/CONTRIBUTING.md
In the section Adding new dependencies, the sentence "please be sure that is is well-maintained and trustworthy" contains a typo: "is is" corrected to "**it is**".
> Typo corrections Update CONTRIBUTING.md

- ui/shared/TruncatedValue.tsx
- ui/tokenInstance/details/TokenInstanceMetadataInfo.tsx
- ui/tokenInstance/metadata/MetadataItemPrimitive.tsx
> Do not display empty NFT attributes

- docs/CONTRIBUTING.md
Typos and grammatical inconsistencies correction.
1. **"your need"** — This phrase appears twice, but it should be **"you need"** for proper grammar.
- **Original**: "Include only secrets your need."
- **Corrected**: "Include only secrets you need."
2. **"If your changes only related"** — This sentence is missing the verb "are."
- **Original**: "If your changes only related to the logic of the app..."
- **Corrected**: "If your changes are only related to the logic of the app..."
3. **"in all test for React components"** — It should be "tests" (plural).
- **Original**: "please do not import package `@testing-library/react` directly in your test suites, instead use imports from `jest/lib` utility."
- **Corrected**: "please do not import the package `@testing-library/react` directly in your …
> Typos Update CONTRIBUTING.md

- configs/app/ui/views/address.ts
- configs/envs/.env.zilliqa_prototestnet
- deploy/tools/envs-validator/schema.ts
- deploy/tools/envs-validator/test/.env.base
- docs/ENVS.md
- types/api/contracts.ts
- types/client/contract.ts
- ui/verifiedContracts/VerifiedContractsFilter.tsx
Resolves #2427
Added `NEXT_PUBLIC_VIEWS_CONTRACT_LANGUAGE_FILTERS` variable to customize language type filter on verified contracts page.
> Zilliqa: filter for Scilla contracts

- deploy/scripts/favicon_generator.sh
Without this change, the script tries to execute an `index.js` located in a folder that does not have such a file.
Use the correct folder, that is, the current working directory, to run the favicon generator.
None.
Running the script now also triggers a `yarn install` in the relevant directory.
> fix(deploy-script): favicon generator

- docs/ENVS.md
- lib/metadata/__snapshots__/generate.test.ts.snap
- lib/metadata/templates/description.ts
resolves https://github.com/blockscout/frontend/issues/2460
> change default description

- configs/envs/.env.main
- lib/api/resources.ts
- lib/hooks/useFetch.tsx
- mocks/config/network.ts
- playwright/fixtures/mockConfigResponse.ts
- playwright/fixtures/mockContractReadResponse.ts
- playwright/fixtures/mockTextAd.ts
- ui/addressVerification/steps/AddressVerificationStepAddress.pw.tsx
- ui/addressVerification/steps/AddressVerificationStepSignature.pw.tsx
- ui/pages/Marketplace.pw.tsx
- ui/pages/MarketplaceApp.pw.tsx
- ui/pages/SearchResults.pw.tsx
- ui/shared/Page/PageTitle.pw.tsx
- ui/shared/nft/NftMedia.pw.tsx
- ui/shared/pagination/useQueryWithPages.test.tsx
- ui/snippets/auth/useLogout.ts
- ui/snippets/footer/Footer.pw.tsx
- ui/snippets/header/Burger.pw.tsx
- ui/snippets/navigation/vertical/NavigationDesktop.pw.tsx
- ui/snippets/networkMenu/NetworkMenu.pw.tsx
- ui/snippets/searchBar/SearchBar.pw.tsx
- ui/snippets/topBar/TopBar.pw.tsx
In addition to deleting the API token cookie, we should call the corresponding API endpoint whenever the user logs out.
> Call the API logout endpoint when the user logs out

- ui/games/CapybaraRunner.tsx
resolves https://github.com/blockscout/frontend/issues/2506
> Add the text for the CapyRun game

- eslint.config.mjs
- ui/address/tokenSelect/TokenSelect.tsx
- ui/marketplace/Banner/FeaturedApp.tsx
- ui/marketplace/MarketplaceAppCardLink.tsx
- ui/marketplace/MarketplaceAppModalLink.tsx
- ui/marketplace/MarketplaceDisclaimerModal.tsx
- ui/shared/NextLink.tsx
- ui/shared/chart/ChartWidget.tsx
- ui/shared/links/LinkInternal.tsx
- ui/shared/stats/StatsWidget.tsx
- ui/snippets/navigation/vertical/NavLink.tsx
- ui/snippets/searchBar/SearchBarSuggest/SearchBarSuggestApp.tsx
- ui/snippets/searchBar/SearchBarSuggest/SearchBarSuggestItem.tsx
resolves https://github.com/blockscout/frontend/issues/2536
> remove nextjs link prefetch

- types/api/txInterpretation.ts
- ui/shared/tx/interpretation/TxInterpretation.tsx
resolves https://github.com/blockscout/frontend/issues/2522 and https://github.com/blockscout/frontend/issues/2514
> Create new Type to show DEX tag in summary header

- lib/contexts/rewards.tsx
- mocks/rewards/rewardsConfig.ts
- types/api/rewards.ts
- ui/pages/MyProfile.tsx
- ui/rewards/login/RewardsLoginModal.tsx
- ui/rewards/login/steps/LoginStepContent.tsx
- ui/snippets/auth/AuthModal.tsx
- ui/snippets/auth/screens/AuthModalScreenConnectWallet.tsx
- ui/snippets/auth/screens/AuthModalScreenSelectMethod.tsx
- ui/snippets/auth/screens/AuthModalScreenSuccessEmail.tsx
- ui/snippets/auth/screens/AuthModalScreenSuccessWallet.tsx
- ui/snippets/auth/types.ts
- ui/snippets/auth/useSignInWithWallet.ts
- ui/snippets/user/profile/UserProfileDesktop.tsx
- ui/snippets/user/profile/UserProfileMobile.tsx
> UX changes for BS / Merits login

- lib/api/resources.ts
- lib/api/useQueryClientConfig.tsx
- ui/snippets/auth/AuthModal.tsx
- [don't throw on "Too many requests" error from 3rd-party APIs](https://github.com/blockscout/frontend/pull/2572/commits/42c1a96f0ae685695465dcdb84a9c174114dd4e1)
- [don't trap focus and block scroll in AuthModal](https://github.com/blockscout/frontend/pull/2572/commits/eeeadb12cd3d03e6966e8fd8894529121107f8f2)
- [update paths for 3rd party resources](https://github.com/blockscout/frontend/pull/2572/commits/efa17a92ed71d173536b46ff87c0abb25f0d5b7e)
> Release v1.37.6

- ui/address/tokenSelect/TokenSelectItem.tsx
- ui/shared/address/AddressAddToWallet.tsx
Previously, using "Number(data.token.decimals) || 18" caused a valid token.decimals value of 0 to fall back to 18. This commit updates the logic to correctly use 0 when defined, ensuring accurate calculations for tokens with 0 decimals.
This pull request addresses a bug in the file `ui/address/tokenSelect/TokenSelectItem.tsx`. When `data.token.decimals` is 0 (a valid value for some ERC20 tokens), the current logic incorrectly falls back to 18 because 0 is falsy in JavaScript. This change updates the logic to properly respect a 0 value, ensuring correct token amount calculations.
Fixes #2635 
- Update the token decimals assignment in `ui/address/tokenSelect/TokenSelectItem.tsx`   
- This change ensures that if `data.token.decimals` is 0, it is used as the valid value rather than falling …
> fix: correctly handle token.decimals when value is 0

- ui/shared/AccountActionsMenu/AccountActionsMenu.tsx
- ui/shared/AccountActionsMenu/items/TokenInfoMenuItem.tsx
- ui/snippets/auth/AuthGuard.tsx
> `Add token info` button is missing for accounts without an email

- .github/workflows/deploy-review.yml
- .vscode/tasks.json
- configs/envs/.env.tac
- tools/preset-sync/index.ts
- ui/shared/entities/address/AddressEntityTacTon.tsx
Some TON addresses can contain special characters, so we need to encode them to create the correct link to the TON explorer.
Example of an incorrect link: https://explorer.tac.build/operation/0x8d6da74a1d62eed2435368c7b2b770dc58e27c0ebc42c5d36cb4eb1ec9df04c1
> Encode the address hash for links to the TON chain

- ui/shared/TokenTransfer/TokenTransferListItem.tsx
resolves https://github.com/blockscout/frontend/issues/2434
> Long token transfer value lacks word-break
