blockscout/frontend

ui/home/IndexingAlertIntTxs.tsx
resolves https://github.com/blockscout/frontend/issues/1149
=> fix alert bg

lib/regexp.ts, ui/tx/details/TxRevertReason.tsx
resolves https://github.com/blockscout/frontend/issues/1117
=> support no-hex revert reason

configs/app/api.ts
resolves https://github.com/blockscout/frontend/issues/1158
=> add socket port

ui/address/contract/ContractCode.tsx, ui/pages/ContractVerification.tsx
=> Add ability to re-verify partially verified contracts from UI

ui/shared/nft/NftMedia.tsx, ui/shared/nft/useNftMediaType.tsx
=> reduce /node-api/media-type calls, when some nft media have the same urls

ui/pages/Address.tsx
resolves https://github.com/blockscout/frontend/issues/1185
=> hide some address tabs if no content

ui/pages/SearchResults.tsx
=> fix links in the browser history after a search redirect

ui/shared/logs/LogDecodedInputDataHeader.tsx
=> Long 'Call' field value breaks responsive UI on Transaction details page

ui/snippets/searchBar/SearchBarSuggest/SearchBarSuggest.tsx
resolves https://github.com/blockscout/frontend/issues/1241
=> fix suggest scroll

ui/pages/Token.tsx
resolves https://github.com/blockscout/frontend/issues/1240
=> nft pagination fix

nextjs/PageNextJs.tsx
resolves https://github.com/blockscout/frontend/issues/1253
=> large preview image in tg

deploy/scripts/make_envs_script.sh
=> double quotes in NEXT_PUBLIC_MAINTENANCE_ALERT_MESSAGE cause an error

ui/watchlist/WatchlistTable/WatchListAddressItem.tsx
resolves https://github.com/blockscout/frontend/issues/1305
=> fix nan net worth for an empty address

deploy/values/review-l2/values.yaml.gotmpl, types/api/l2Withdrawals.ts, types/api/transaction.ts, ui/shared/verificationSteps/VerificationSteps.tsx, ui/tx/TxDetails.tsx, ui/tx/details/TxDetailsWithdrawalStatus.tsx
=> "Claim funds" button for OP bridge

pages/api/media-type.ts
=> NFT media is not displayed

ui/snippets/navigation/NavLink.tsx
=> external icon in menu

nextjs/csp/policies/googleAnalytics.ts, ui/shared/GoogleAnalytics.tsx
=> GA: fix inline-script CSP issue

lib/api/resources.ts
resolves https://github.com/blockscout/frontend/issues/1367
=> fix account paths

mocks/tokens/tokenInstance.ts, stubs/token.ts, types/api/token.ts, ui/pages/Token.tsx, ui/pages/TokenInstance.tsx, ui/token/TokenInventory.pw.tsx, ui/token/TokenInventory.tsx, ui/token/TokenInventoryItem.tsx, ui/tokenInstance/TokenInstanceDetails.pw.tsx, ui/tokenInstance/TokenInstanceDetails.tsx
resolves https://github.com/blockscout/frontend/issues/1346
=> remove token info from instance

ui/marketplace/MarketplaceAppCard.tsx
resolves https://github.com/blockscout/frontend/issues/1382
=> marketplace border radius

lib/tx/sortTxs.ts, types/api/fee.ts, ui/home/LatestTxsItem.tsx, ui/home/LatestTxsItemMobile.tsx, ui/tx/TxDetailsWrapped.tsx, ui/tx/details/TxDetailsFeePerGas.tsx, ui/txs/TxAdditionalInfoContent.tsx, ui/txs/TxsListItem.tsx, ui/txs/TxsTableItem.tsx
resolves https://github.com/blockscout/frontend/issues/1387
=> tx fee can be null

ui/stats/NumberWidgetsList.tsx
resolves https://github.com/blockscout/frontend/issues/1399
=> stats second fix

README.md
https://docs.blockscout.com/for-developers/deployment/manual-deployment-guide
=> Add link in Readme to the Manual deployment guide with backend and microservices

next.config.js, nextjs/csp/policies/walletConnect.ts, package.json, playwright/TestApp.tsx, ui/address/contract/ContractConnectWallet.tsx, ui/addressVerification/steps/AddressVerificationStepSignature.tsx, ui/shared/Web3ModalProvider.tsx, ui/snippets/walletMenu/useWallet.tsx, yarn.lock
=> update `Web3Modal` to v3

ui/snippets/walletMenu/WalletTooltip.tsx
Resolves https://github.com/blockscout/frontend/issues/1434
=> Fix tooltip for `connect wallet` button

ui/snippets/searchBar/SearchBar.tsx, ui/snippets/searchBar/SearchBarInput.tsx
fixes https://github.com/blockscout/frontend/issues/1411 
fixes https://github.com/blockscout/frontend/issues/1410
=> Search focus test

ui/address/tokens/ERC20TokensTableItem.tsx, ui/shared/address/AddressAddToWallet.tsx, ui/tokens/TokensTableItem.tsx
=> hide metamask icon in tables

ui/graphQL/GraphQL.tsx
fixes https://github.com/blockscout/frontend/issues/1454
=> fix graphql color mode sync

ui/shared/Tabs/TabsWithScroll.tsx
fixes https://github.com/blockscout/frontend/issues/1502
=> tabs re-render fix

ui/shared/layout/LayoutApp.tsx
Resolves https://github.com/blockscout/frontend/issues/1487
=> Remove alerts from the Marketplace app page

lib/mixpanel/utils.ts, ui/marketplace/MarketplaceAppCard.tsx, ui/marketplace/useMarketplace.tsx, ui/snippets/walletMenu/WalletMenuContent.tsx, ui/snippets/walletMenu/WalletMenuDesktop.tsx, ui/snippets/walletMenu/WalletMenuMobile.tsx
Resolves https://github.com/blockscout/frontend/issues/1455
=> Add new mixpanel events

ui/shared/TokenTransfer/TokenTransferFilter.tsx
fix https://github.com/blockscout/frontend/issues/1506
=> token transfer filter fix

ui/address/contract/ContractConnectWallet.tsx, ui/snippets/walletMenu/WalletMenuDesktop.tsx, ui/snippets/walletMenu/WalletMenuMobile.tsx, ui/snippets/walletMenu/useWallet.tsx
=> Connect wallet event sent twice

ui/address/contract/utils.ts
=> Contract interaction: nested tuple values are not parsed properly

types/api/tokenTransfer.ts, ui/shared/TokenTransfer/TokenTransferListItem.tsx, ui/shared/TokenTransfer/TokenTransferTableItem.tsx, ui/token/TokenTransfer/TokenTransferListItem.tsx, ui/token/TokenTransfer/TokenTransferTableItem.tsx, ui/tx/NftTokenTransferSnippet.tsx, ui/tx/state/TxStateTokenIdList.tsx
resolves https://github.com/blockscout/frontend/issues/1538
=> token id can be null

package.json, pages/_app.tsx, yarn.lock
fixes https://github.com/blockscout/frontend/issues/1566
=> remove unnecessary focus

lib/web3/client.ts, ui/block/useBlockQuery.tsx, ui/block/useBlockTxQuery.tsx, ui/block/useBlockWithdrawalsQuery.tsx, ui/pages/Transaction.tsx, ui/tx/TxDetails.tsx, ui/tx/TxDetailsDegraded.tsx, ui/tx/TxUserOps.tsx, ui/userOps/UserOpsContent.tsx
Fix issues when page content (tx, block) is not loaded when no RPC URL is provided for the app instance
=> hotfix: fix error in degraded views when no RPC URL provided

lib/web3/client.ts, ui/block/useBlockQuery.tsx, ui/block/useBlockTxQuery.tsx, ui/block/useBlockWithdrawalsQuery.tsx, ui/marketplace/useMarketplaceCategories.tsx, ui/pages/Address.tsx, ui/pages/Transaction.tsx, ui/tx/TxDetails.tsx, ui/tx/TxDetailsDegraded.tsx, ui/tx/TxUserOps.tsx, ui/userOps/UserOpsContent.tsx
Fixes incorrect grouping of categories on marketplace
=> Fix categories

nextjs/nextjs-routes.d.ts, stubs/RPC.ts, types/api/address.ts, ui/address/AddressDetails.pw.tsx, ui/address/AddressDetails.tsx, ui/address/details/AddressCounterItem.tsx, ui/address/utils/useAddressCountersQuery.ts, ui/address/utils/useAddressQuery.ts, ui/pages/Address.tsx
=> Graceful service degradation: address page

ui/userOp/UserOpDetails.tsx
=> Fix minor typo

docs/ENVS.md
the closest thing is the "Get Started" button link at https://docs.walletconnect.com/web3modal/react/about
=> Fix broken link in ENVS.md

ui/marketplace/useMarketplaceApps.tsx
Resolves https://github.com/blockscout/frontend/issues/1611
=> Sort dapps by favourite

types/api/contract.ts, ui/address/contract/ContractMethodCallable.tsx, ui/address/contract/ContractRead.tsx, ui/address/contract/useContractAbi.tsx
=> `outputs` field is not required for contract read method

ui/address/tokens/AddressCollections.tsx, ui/shared/EmptySearchResult.tsx, ui/token/TokenInventory.tsx
=> Not possible to remove address filter in token inventory for an address with no NFTs

ui/shared/pagination/useQueryWithPages.ts
fixes https://github.com/blockscout/frontend/issues/1631
=> fix navigation reset

ui/blocks/BlocksTable.tsx, ui/shared/Page/PageTitle.tsx
fixes https://github.com/blockscout/frontend/issues/1656
=> fixes for no miner

lib/mixpanel/utils.ts, ui/marketplace/useMarketplaceWallet.tsx, ui/pages/MarketplaceApp.tsx
Resolves https://github.com/blockscout/frontend/issues/1632
=> Add mixpanel events to operations in dapps

configs/envs/.env.eth, ui/address/ensDomains/AddressEnsDomains.tsx, ui/shared/entities/address/AddressEntity.tsx
=> truncate domain in domains popup

lib/contexts/addressHighlight.tsx, theme/global.ts, theme/globals/address-entity.ts, ui/shared/entities/address/AddressEntity.tsx
=> improve perf of highlighting same address in lists

configs/envs/.env.sepolia, types/api/userOps.ts, ui/userOp/UserOpRaw.tsx
resolves https://github.com/blockscout/frontend/issues/1677
=> Support raw format of v0.7 user ops

ui/shared/nft/NftMedia.tsx, ui/token/TokenInventory.tsx
=> Incorrect NFT media placeholder when navigating between pages

mocks/tokens/tokenHolders.ts, stubs/token.ts, types/api/token.ts
=> Remove the use of the token object from the response of the `api/v2/tokens/<address>/holders` endpoint.

ui/shared/entities/token/TokenEntity.tsx
resolves https://github.com/blockscout/frontend/issues/1714
=> fix token icon fallback

lib/token/metadata/attributesParser.ts
resolves https://github.com/blockscout/frontend/issues/1713
=> metadata date fix

configs/envs/.env.sepolia, deploy/values/review/values.yaml.gotmpl, docs/ENVS.md, nextjs/csp/policies/ad.ts, package.json, types/client/adProviders.ts, ui/shared/ad/AdBanner.tsx, ui/shared/ad/GetitBanner.tsx, yarn.lock
resolves https://github.com/blockscout/frontend/issues/1634
=> Getit ad banner

ui/address/contract/methodForm/ContractMethodForm.tsx, ui/address/contract/methodForm/useFormatFieldValue.tsx, ui/address/contract/methodForm/useValidateField.tsx, ui/address/contract/methodForm/utils.ts
=> bugfix: Cannot convert string to buffer while write to the contract

playwright/TestApp.tsx, ui/shared/Web3ModalProvider.tsx
resolves https://github.com/blockscout/frontend/issues/1729
=> enable email for wallet connect

nextjs/getServerSideProps.ts, pages/login.tsx
making /login page unavailable for production
=> hide login page if no proxy needed

.gitignore, deploy/values/review/values.yaml.gotmpl, lib/metadata/getApiDataForSocialPreview.ts, lib/metadata/getPageOgType.ts, lib/metadata/templates/description.ts, lib/metadata/templates/title.ts, lib/mixpanel/getPageType.ts, lib/monitoring/metrics.ts, nextjs/nextjs-routes.d.ts, package.json, pages/_document.tsx, pages/api/log.ts, pages/api/metrics.ts, prometheus.yml, yarn.lock
- Added Prometheus to track requests from social preview bots (twitter, facebook)
=> Monitoring: social preview bots request counter

ui/pages/Transaction.tsx
=> Trust 422 from api for invalid params

ui/tx/internals/TxInternalsList.tsx, ui/tx/internals/TxInternalsTable.tsx
fixes internal transactions pagination
=> fix internal tx keys

lib/api/resources.ts, mocks/address/coinBalanceHistory.ts, types/api/address.ts, ui/address/coinBalance/AddressCoinBalanceChart.tsx, ui/shared/chart/ChartWidget.tsx
resolves https://github.com/blockscout/frontend/issues/1775
=> coin balance history chart new type and custom empty text

ui/gasTracker/GasTrackerPriceSnippet.tsx, ui/shared/gas/GasInfoTooltipRow.tsx
=> Fix gas tracker time when backend returns 0

ui/shared/address/AddressFromTo.tsx
=> Addresses not rendered in token actions on Transaction page (Firefox)

ui/address/contract/ContractCode.tsx
*[Provide a brief description of the changes or enhancements introduced by this pull request and explain motivation behind them. Cite any related issue(s) or bug(s) that it addresses using the [format](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/) `Fixes #123` or `Resolves #456`.]*
*[Specify the changes or additions made in this pull request. Please mention if any changes were made to the ENV variables]*
*[Describe any breaking or incompatible changes introduced by this pull request. Specify how users might need to modify their code or configurations to accommodate these changes.]*
*[Include any additional information, context, or screenshots that may be helpful for reviewers.]*
=> change license tooltip text

playwright/TestApp.tsx, playwright/fixtures/mockEnvs.ts, playwright/fixtures/mockTextAd.ts, playwright/lib.tsx, ui/pages/Blocks.pw.tsx, ui/pages/ShibariumDeposits.pw.tsx, ui/pages/ShibariumWithdrawals.pw.tsx, ui/pages/Token.pw.tsx, ui/pages/Tokens.pw.tsx, ui/pages/Validators.pw.tsx, ui/pages/ZkEvmL2Deposits.pw.tsx, ui/pages/ZkEvmL2Withdrawals.pw.tsx, ui/snippets/searchBar/SearchBar.pw.tsx
- fix flaky tests
- make separate wagmi config for tests
=> fix flaky tests

ui/address/tokens/NFTItem.tsx, ui/shared/nft/NftMedia.tsx, ui/shared/nft/NftVideo.tsx, ui/shared/nft/NftVideoFullscreen.tsx, ui/shared/nft/utils.ts, ui/token/TokenInventoryItem.tsx
resolves https://github.com/blockscout/frontend/issues/1872
=> remove video autoplay from lists

ui/tx/TxInternals.tsx
fixes https://github.com/blockscout/frontend/issues/1890
=> fix internal txs sorting

nextjs/csp/policies/app.ts
- Add CSP for Metadata service
=> Release v1.30.0 fixes

nextjs/csp/policies/app.ts, ui/marketplace/MarketplaceListWithScores/AppLink.tsx
- fixes a CSP that is now blocking a banner on the marketplace page
- fixes https://github.com/blockscout/frontend/issues/1909
=> Hotfix: content security policy and image size issues

playwright/fixtures/mockEnvs.ts, ui/pages/SearchResults.pw.tsx, ui/pages/SearchResults.tsx, ui/shared/search/utils.ts, ui/snippets/searchBar/SearchBar.pw.tsx
resolves https://github.com/blockscout/frontend/issues/1900
=> remove unsupported features from search results

lib/hooks/useAdblockDetect.tsx, ui/shared/DetailsSponsoredItem.tsx, ui/shared/ad/AdBanner.tsx, ui/shared/ad/TextAd.tsx
resolves https://github.com/blockscout/frontend/issues/1980
=> Adblock detect improvement

ui/shared/nft/useNftMediaInfo.tsx
=> Fix lazy loading on NFT Inventory view

docs/BUILD-TIME_ENVS.md, docs/DEPRECATED_ENVS.md, docs/ENVS.md
=> Add supported frontend versions column in ENVS.md

lib/address/useAddressMetadataInfoQuery.ts, playwright/mocks/lib/growthbook/useFeatureValue.js, ui/address/AddressAccountHistory.tsx, ui/address/AddressBlocksValidated.tsx, ui/address/AddressCoinBalance.tsx, ui/address/AddressInternalTxs.tsx, ui/address/AddressLogs.tsx, ui/address/AddressTokenTransfers.tsx, ui/address/AddressTokens.tsx, ui/address/AddressTxs.tsx, ui/address/AddressUserOps.tsx, ui/address/AddressWithdrawals.tsx, ui/address/utils/useAddressQuery.ts, ui/address/utils/useCheckDomainNameParam.ts, ui/pages/Address.tsx, ui/shared/AppActionButton/useAppActionData.tsx
=> Resolve BENS names from URL directly to address page

ui/address/contract/ABI/useCallMethodWalletClient.ts
=> Contract `Write` method returns a checksum error

lib/api/resources.ts, mocks/ens/domain.ts, mocks/ens/events.ts, package.json, stubs/ENS.ts, types/api/ens.ts, ui/address/ensDomains/AddressEnsDomains.pw.tsx, ui/address/ensDomains/AddressEnsDomains.tsx, ui/nameDomain/NameDomainDetails.tsx, ui/nameDomain/NameDomainHistory.tsx, ui/nameDomain/history/NameDomainHistoryListItem.tsx, ui/nameDomain/history/NameDomainHistoryTable.tsx, ui/nameDomain/history/NameDomainHistoryTableItem.tsx, ui/nameDomain/history/utils.ts, ui/nameDomains/NameDomainsActionBar.tsx, ui/nameDomains/NameDomainsListItem.tsx, ui/nameDomains/NameDomainsTable.tsx, ui/nameDomains/NameDomainsTableItem.tsx, ui/pages/NameDomain.tsx, ui/pages/NameDomains.tsx, ui/shared/entities/ens/EnsEntity.tsx, yarn.lock
Migrate ENS types to `bens-types` package
=> Migrate to `bens-types`

ui/snippets/walletMenu/WalletTooltip.tsx
Resolves https://github.com/blockscout/frontend/issues/1993
=> Wallet tooltip fixes

lib/mixpanel/index.ts, lib/mixpanel/useInit.tsx, lib/mixpanel/userProfile.ts, types/utils.ts, ui/snippets/walletMenu/useWallet.tsx
=> Mixpanel profiles

ui/shared/search/utils.ts
=> Quick search - move BENS results to the top

ui/shared/stats/StatsWidget.tsx
resolves https://github.com/blockscout/frontend/issues/1974
=> change counter labels to H2

ui/snippets/walletMenu/WalletMenuDesktop.tsx
Fixes https://github.com/blockscout/frontend/issues/2111
=> Fix "connect wallet" button tooltip

ui/marketplace/useMarketplace.tsx, ui/marketplace/useMarketplaceApps.tsx, ui/shared/EmptySearchResult.tsx
Fixes https://github.com/blockscout/frontend/issues/2130
=> Fix marketplace search query

ui/pages/SearchResults.tsx, ui/snippets/searchBar/SearchBar.tsx, ui/snippets/searchBar/useSearchQuery.tsx
resolves https://github.com/blockscout/frontend/issues/2077
=> check redirect only on search bar submit

lib/hooks/useTimeAgoIncrement.tsx, ui/address/accountHistory/AddressAccountHistoryListItem.tsx, ui/address/accountHistory/AddressAccountHistoryTableItem.tsx, ui/shared/TimeAgoWithTooltip.tsx
resolves https://github.com/blockscout/frontend/issues/2169
=> fix time ago

ui/shared/entities/address/AddressEntityContentProxy.tsx
resolves https://github.com/blockscout/frontend/issues/2175
=> Display shortened address for proxy contracts

lib/api/useApiQuery.tsx
=> Cancel previous search queries when typing

ui/snippets/searchBar/SearchBar.tsx, ui/snippets/searchBar/useQuickSearchQuery.tsx
=> Main search vs search on page

lib/address/getCheckedSummedAddress.ts, ui/pages/Address.tsx
=> Display checksum-ed addresses

ui/contractVerification/fields/ContractVerificationFieldSources.tsx, ui/contractVerification/methods/ContractVerificationMultiPartFile.tsx, ui/contractVerification/methods/ContractVerificationVyperMultiPartFile.tsx, ui/shared/forms/DragAndDropArea.tsx, ui/shared/forms/utils/files.ts
=> Pass the file path when verifying a multi-part contract

lib/web3/useAddOrSwitchChain.tsx
=> `Unrecognized chain ID` error when adding network via mobile MetaMask

deploy/tools/affected-tests/yarn.lock, deploy/tools/envs-validator/yarn.lock, deploy/tools/feature-reporter/yarn.lock, yarn.lock
Update NPM packages version to address vulnerability issues
=> Fix security vulnerability issues

configs/app/features/index.ts, configs/app/features/xStarScore.ts, configs/envs/.env.eth_sepolia, deploy/tools/envs-validator/schema.ts, docs/ENVS.md, lib/api/resources.ts, lib/xStarScore/useFetchXStarScore.ts, types/api/address.ts, ui/pages/Address.tsx
resolves https://github.com/blockscout/frontend/issues/2314
added NEXT_PUBLIC_XSTAR_SCORE_URL variable 
=> Humanity score integration

types/api/addressParams.ts, ui/shared/entities/address/AddressEntityContentProxy.tsx
resolves https://github.com/blockscout/frontend/issues/2358
=> add filecoin address for proxy implementations

configs/envs/.env.eth_sepolia, lib/mixpanel/utils.ts, ui/rewards/login/RewardsLoginModal.tsx, ui/rewards/login/steps/LoginStepContent.tsx, ui/snippets/auth/AuthModal.tsx, ui/snippets/auth/screens/AuthModalScreenSuccessWallet.tsx
Added an email step when logging into merits
=> Adding an email when logging into merits

ui/address/details/AddressImplementations.tsx
find one more place without robust address
=> one more place with filecoin

ui/address/AddressTokens.tsx
=> erc20 query fix

types/api/contracts.ts, ui/verifiedContracts/VerifiedContractsTableItem.tsx
=> Zilliqa: "Verified contracts" page crashes on desktop

lib/xStarScore/useFetchXStarScore.ts, types/api/address.ts, ui/pages/Address.tsx
resolves https://github.com/blockscout/frontend/issues/2391
=> fix xstar responce format

package.json, yarn.lock
=> up dappscout-iframe for react version compatibility

ui/blocks/BlocksTableItem.tsx
=> fix block miner highlight style

ui/tx/TxSubHeading.tsx
resolves https://github.com/blockscout/frontend/issues/2322
=> Interpretation stub for failed txs

ui/pages/Address.tsx, ui/token/TokenPageTitle.tsx
resolves https://github.com/blockscout/frontend/issues/2465
=> Explorers section: bring hashes to lower case in the url

types/api/zkEvmL2.ts
1. **File**: `types/api/zkEvmL2.ts`
- Fixed "responce" to "response" (Line 72).
- Improved code accuracy by fixing the typographical error.
- Enhanced the clarity and professionalism of the codebase.
=> typo-Update zkEvmL2.ts

deploy/tools/affected-tests/yarn.lock, deploy/tools/envs-validator/yarn.lock, deploy/tools/favicon-generator/yarn.lock, deploy/tools/feature-reporter/yarn.lock, theme/yarn.lock, yarn.lock
Update package versions to mitigate security vulnerabilities.
=> Fix dependabot alerts

ui/shared/entities/address/AddressEntity.tsx
resolves https://github.com/blockscout/frontend/issues/2475
=> Filecoin: display address id instead of hash

lib/address/getCheckedSummedAddress.ts, ui/pages/Address.tsx
=> Rootstock checksum is not applied on the address page

ui/address/contract/useContractTabs.tsx
resolves https://github.com/blockscout/frontend/issues/2524
=> Redundant request to MUD API on the Contract tab of Token page

ui/address/details/AddressCounterItem.tsx, ui/address/tokenSelect/TokenSelect.tsx
resolves https://github.com/blockscout/frontend/issues/2378
=> Address ERC-20 tokens tab navigation issue

ui/searchResults/SearchResultListItem.tsx, ui/searchResults/SearchResultTableItem.tsx
fixes https://github.com/blockscout/frontend/issues/2454
=> Search: open dapp info for external dapps fix

.github/workflows/deploy-main.yml, .github/workflows/deploy-review-l2.yml, .github/workflows/deploy-review.yml, .github/workflows/e2e-tests.yml, .github/workflows/publish-image.yml, .github/workflows/release.yml
- use `latest` tag only for release builds
- for builds from the main branch use `unstable` tag
=> Update tag convention for docker images

lib/contexts/chakra.tsx
fixes https://github.com/blockscout/frontend/issues/2264
=> fix incorrect color mode

lib/address/getCheckedSummedAddress.ts
=> Rootstock checksum is applied to all chains

lib/socket/types.ts, lib/socket/useSocketChannel.tsx, ui/address/contract/ContractDetails.pw.tsx, ui/address/contract/ContractDetails.tsx, ui/home/latestDeposits/LatestOptimisticDeposits.tsx, ui/snippets/footer/IntTxsIndexingStatus.tsx, ui/snippets/header/alerts/IndexingBlocksAlert.tsx
- Fixes #2618
- Fixes #2434 
- Fixes #2612 
=> Socket updates: on-demand contract verification fix, indexing event rename

package.json, yarn.lock
Update app dependencies to their latest versions
=> Bump `reown`, `wagmi` and `viem`

ui/snippets/auth/screens/AuthModalScreenOtpCode.tsx
Fixes the issue when there was a significant delay in sending the request for a new OTP
=> Reset the reCAPTCHA after the user attempts to resend the OTP

mocks/contract/info.ts, types/api/contract.ts, ui/address/contract/ContractDetails.tsx, ui/address/contract/alerts/ContractDetailsAlertProxyPattern.pw.tsx, ui/address/contract/alerts/ContractDetailsAlertProxyPattern.tsx, ui/address/contract/alerts/ContractDetailsAlerts.pw.tsx, ui/address/contract/alerts/ContractDetailsAlerts.pwstory.tsx, ui/address/contract/alerts/ContractDetailsAlerts.tsx, ui/address/contract/useContractDetailsTabs.tsx, ui/address/contract/useContractTabs.tsx
=> Remove `proxy_type` field from SmartContract model

lib/contexts/rewards.tsx, ui/address/contract/methods/useCallMethodWalletClient.ts, ui/addressVerification/steps/AddressVerificationStepSignature.tsx, ui/snippets/auth/useSignInWithWallet.ts
=> Auth: Switch the chain before signing the message when the user logs in with their wallet

ui/shared/address/AddressFromTo.tsx, ui/shared/address/utils.ts
=> Invalid case-sensitive comparison in AddressFromTo

types/api/contract.ts, ui/address/contract/alerts/ContractDetailsAlertProxyPattern.tsx
=> Reflect new smart-contract proxy patterns in UI

package.json, ui/marketplace/useMarketplaceWallet.tsx, yarn.lock
The new version adds support of contract deployment: https://github.com/blockscout/iframe/commit/6ae637b280064aaf618d1cf773942ebd0d101317
=> Update dappscout-iframe lib

ui/snippets/user/wallet/UserWalletButton.tsx
=> `Connect` button tooltip positioned in the corner

lib/growthbook/useLoadFeatures.ts, next.config.js, nextjs/PageMetadata.tsx, nextjs/PageNextJs.tsx, pages/_app.tsx, ui/shared/layout/Layout.tsx, ui/shared/layout/LayoutApp.tsx, ui/shared/layout/LayoutError.tsx, ui/shared/layout/LayoutHome.tsx, ui/shared/layout/LayoutSearchResults.tsx, ui/shared/layout/components/Root.tsx, ui/shared/layout/components/index.tsx
=> Page meta tags are not generated on the server

lib/hooks/useNavItems.tsx
fixes https://github.com/blockscout/frontend/issues/2711
=> top validators -> validators

ui/marketplace/AppSecurityReport.tsx, ui/marketplace/ContractSecurityReport.tsx
=> Buggy display of Security Score in mobile version

docs/ENVS.md, ui/pages/Address.tsx, ui/shared/NetworkExplorers.tsx, ui/token/TokenPageTitle.tsx
resolves https://github.com/blockscout/frontend/issues/2761
paths in NEXT_PUBLIC_NETWORK_EXPLORERS can be templates
=> Explorer links - add toggle for lowercase hash

ui/advancedFilter/filters/AgeFilter.tsx
fixes https://github.com/blockscout/frontend/issues/2762
=> advanced filter: fix date input

ui/txs/sortTxs.ts
resolves https://github.com/blockscout/frontend/issues/2759
=> fix tx socket sorting

configs/envs/.env.arbitrum, configs/envs/.env.optimism, package.json, ui/home/Stats.tsx, ui/home/indicators/useChartDataQuery.tsx, ui/home/indicators/utils/indicators.tsx, ui/txs/TxsStats.tsx, yarn.lock
resolves https://github.com/blockscout/frontend/issues/2702
=> Support op stack operational transactions

lib/router/useEtherscanRedirects.ts, nextjs/redirects.js, ui/pages/Address.tsx, ui/pages/Stats.tsx, ui/pages/Token.tsx, ui/pages/Transaction.tsx
=> Support redirects for known address discrepancies

lib/mixpanel/useInit.tsx
=> Change persistence of Mixpanel config

ui/address/contract/methods/form/resultPublicClient/ItemPrimitive.tsx
=> Contract method output: remove the tooltip with the value divided by 10**18

ui/snippets/topBar/NetworkMenu.tsx, ui/snippets/topBar/settings/Settings.tsx
=> UX: add tooltip (setting/chains)

ui/address/contract/methods/form/ContractMethodFieldInput.tsx
=> Bug: number inputs are not disabled

ui/pages/TokenTransfers.tsx
=> UI: Text "Token Transfers"

ui/address/mud/AddressMudTables.tsx, ui/pages/InternalTxs.tsx, ui/pages/TacOperations.tsx, ui/pages/VerifiedContracts.tsx
=> Verified contracts: the message "No verified contracts" briefly appears after clearing the filter input

ui/rewards/dashboard/tabs/ResourcesTab.tsx
Resolves https://github.com/blockscout/frontend/issues/2902
=> Fix link url on the Merits dashboard

README.md, ui/address/contract/alerts/ContractDetailsAlertVerificationSource.tsx, ui/addressVerification/steps/AddressVerificationStepSignature.tsx, ui/apiDocs/EthRpcApi.tsx, ui/apiDocs/RpcApi.tsx, ui/contractVerification/methods/ContractVerificationSolidityFoundry.tsx, ui/contractVerification/methods/ContractVerificationSolidityHardhat.tsx, ui/pages/ApiKeys.tsx, ui/pages/VerifiedAddresses.tsx
resolves https://github.com/blockscout/frontend/issues/2950
=> update docs links

ui/address/contract/useContractTabs.tsx
Fix query condition for mud systems resource on token contract tab
=> Remove unnecessary call of mud systems resource from token contract tab

deploy/scripts/download_assets.sh, deploy/scripts/entrypoint.sh
resolves https://github.com/blockscout/frontend/issues/3029
=> add retries for assets downloading, fail build

deploy/tools/sitemap-generator/next-sitemap.config.js
=> fixed undefined for token pages in sitemap.xml
